spring:
  application:
    name: site-gateway
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:8848
        namespace: 760fd545-42fc-496d-882d-133431b4fb61
        group: DEV_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
logging:
  file:
    name: log/site-gateway.log
server:
  port: 9000
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露