spring:
  application:
    name: site-mod
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:8848
        namespace: 760fd545-42fc-496d-882d-133431b4fb61
        group: DEV_GROUP
#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 2000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 3000
# 日志文件配置
logging:
  file:
    name: log/site-mod.log
server:
  port: 8001
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露